CXX = g++
CXXFLAGS = -std=c++0x
CXXFLAGS += -Wall
CXXFLAGS += -pedantic-errors
CXXFLAGS += -g

OBJS = mod3.o CS162.o Traffic.o

SRCS = CS162.cpp mod3.cpp Traffic.cpp

HEADERS =  CS162.hpp Traffic.hpp

TARGET = mod3

${TARGET}: ${SRCS} ${HEADERS}
	${CXX} ${CXXFLAGS} ${SRCS} -o ${TARGET}

clean: 
	${RM} ${TARGET} *.o *~
